### ISSUE TITLE
Additional instructions

### ISSUE THREAD

**Issue by cpursley** [ruslantalpa/blogdemo#2]
Thanks for putting this together!

Can you write some additional instructions for the README on how to create a user and then authenticate to post/update via the endpoints?

**Comment by ruslantalpa** [comment]
@cpursley 
an old version of the code contained some login functionality but later it got refactored out :)
This should give you an idea how to call /rpc/login, rpc/signup is the same thing. https://github.com/ruslantalpa/blogdemo/blob/8b28867ef47a88efbdc235da5313379389f826f8/frontend/scripts/login.js

**Comment by ruslantalpa** [comment]
If you want to play with this example and extend it, PR's are welcome
